apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-pod-test
  namespace: project-final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-test
  template:
    metadata:
      labels:
        app: pod-test
    spec:
      containers:
      - name: container-test
        image: nginx:latest