apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  kustomize-source: base
  environment: testing
  owner-team: luis-costa

resources:
- namespace.yaml
- deployment-produtor.yaml
- deployment-consumidor.yaml
- deployment-pod-test.yaml
- deployment-pod-test-2.yaml