apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-pod-test-2
  namespace: project-final-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-test-2
  template:
    metadata:
      labels:
        app: pod-test-2
    spec:
      containers:
      - name: container-test
        image: nginx:latest