name: Pylint Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  pylint_check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run Pylint
      run: pylint **/*.py --ignore-patterns=__init__.py --disable=C0114,C0115,C0116 . 